[package]
name = "airline"
version = "0.1.0"
description = "Airline Protocol program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "airline"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.1"

[dev-dependencies]
solana-client = "2.3.0"
solana-sdk = "2.3.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(feature, values(\"custom-heap\", \"custom-panic\", \"anchor-debug\"))",
  "cfg(target_os, values(\"solana\"))"
] }
